use std::{
    net::{IpAddr, Ipv4Addr, SocketAddr},
    path::Path,
    str::FromStr as _,
};

use anyhow::Result;
use serde::{Deserialize, Serialize};
use serde_yaml_ng::{Mapping, Value};

use crate::{
    constants::{network, tun},
    yaml,
};

#[derive(Default, Debug, Clone, PartialEq)]
pub struct IClashTemp(pub Mapping);

impl IClashTemp {
    #[must_use]
    pub fn template() -> Self {
        Self::template_with_ipc::<&Path>(None)
    }

    #[must_use]
    pub fn template_with_ipc<P: AsRef<Path>>(ipc_path: Option<P>) -> Self {
        let mut map = Mapping::new();
        let mut tun_config = Mapping::new();
        let ipc_path = ipc_path
            .as_ref()
            .and_then(|path| path.as_ref().to_str())
            .filter(|path| !path.is_empty());

        tun_config.insert("enable".into(), false.into());
        tun_config.insert("stack".into(), tun::DEFAULT_STACK.into());
        tun_config.insert("auto-route".into(), true.into());
        tun_config.insert("strict-route".into(), false.into());
        tun_config.insert("auto-detect-interface".into(), true.into());
        tun_config.insert(
            "dns-hijack".into(),
            Value::Sequence(tun::DNS_HIJACK.iter().map(|value| Value::from(*value)).collect()),
        );

        #[cfg(not(target_os = "windows"))]
        map.insert("redir-port".into(), network::ports::DEFAULT_REDIR.into());
        #[cfg(target_os = "linux")]
        map.insert("tproxy-port".into(), network::ports::DEFAULT_TPROXY.into());

        map.insert("tun".into(), Value::Mapping(tun_config));
        map.insert("mixed-port".into(), network::ports::DEFAULT_MIXED.into());
        map.insert("socks-port".into(), network::ports::DEFAULT_SOCKS.into());
        map.insert("port".into(), network::ports::DEFAULT_HTTP.into());
        map.insert("log-level".into(), "info".into());
        map.insert("allow-lan".into(), false.into());
        map.insert("ipv6".into(), true.into());
        map.insert("mode".into(), "rule".into());
        #[cfg(unix)]
        let uses_ipc_controller = ipc_path.is_some();
        #[cfg(not(unix))]
        let uses_ipc_controller = false;

        if !uses_ipc_controller {
            map.insert(
                "external-controller".into(),
                network::DEFAULT_EXTERNAL_CONTROLLER.into(),
            );
        }

        if let Some(ipc_path) = ipc_path {
            #[cfg(unix)]
            map.insert("external-controller-unix".into(), ipc_path.into());
            #[cfg(windows)]
            map.insert("external-controller-pipe".into(), ipc_path.into());
        }
        map.insert("secret".into(), "set-your-secret".into());
        map.insert("unified-delay".into(), true.into());

        Self(map)
    }

    pub async fn load_or_template(path: impl AsRef<Path>, ipc_path: Option<&Path>) -> Self {
        match yaml::read_mapping(path).await {
            Ok(map) => Self::from_mapping(map, ipc_path),
            Err(_) => Self::template_with_ipc(ipc_path),
        }
    }

    #[must_use]
    pub fn from_mapping(mut map: Mapping, ipc_path: Option<&Path>) -> Self {
        for (key, value) in Self::template_with_ipc(ipc_path).0 {
            map.entry(key).or_insert(value);
        }
        #[cfg(unix)]
        if ipc_path.is_some() {
            map.remove("external-controller");
            map.remove("external-controller-cors");
        }
        if let Some(Value::String(secret)) = map.get_mut("secret")
            && secret.is_empty()
        {
            *secret = "set-your-secret".into();
        }
        Self(Self::guard(map))
    }

    #[must_use]
    pub fn guard(mut config: Mapping) -> Mapping {
        #[cfg(not(target_os = "windows"))]
        config.insert(
            "redir-port".into(),
            guard_u16(&config, "redir-port", network::ports::DEFAULT_REDIR).into(),
        );
        #[cfg(target_os = "linux")]
        config.insert(
            "tproxy-port".into(),
            guard_u16(&config, "tproxy-port", network::ports::DEFAULT_TPROXY).into(),
        );

        config.insert("mixed-port".into(), Self::guard_mixed_port(&config).into());
        config.insert("socks-port".into(), Self::guard_socks_port(&config).into());
        config.insert("port".into(), Self::guard_port(&config).into());
        if config.contains_key("external-controller") {
            config.insert("external-controller".into(), Self::guard_server_ctrl(&config).into());
        }
        config
    }

    pub fn patch_config(&mut self, patch: &Mapping) {
        for (key, value) in patch {
            self.0.insert(key.clone(), value.clone());
        }
        self.0 = Self::guard(std::mem::take(&mut self.0));
    }

    pub async fn save_config(&self, path: impl AsRef<Path>) -> Result<()> {
        yaml::save_yaml(path, &self.0, Some("# Generated by Clash TUI")).await
    }

    #[must_use]
    pub fn get_client_info(&self) -> ClashInfo {
        let config = &self.0;

        ClashInfo {
            mixed_port: Self::guard_mixed_port(config),
            socks_port: Self::guard_socks_port(config),
            port: Self::guard_port(config),
            server: Self::guard_client_ctrl(config),
            secret: config.get("secret").and_then(scalar_to_string),
        }
    }

    #[must_use]
    pub fn guard_mixed_port(config: &Mapping) -> u16 {
        guard_u16(config, "mixed-port", network::ports::DEFAULT_MIXED)
    }

    #[must_use]
    pub fn guard_socks_port(config: &Mapping) -> u16 {
        guard_u16(config, "socks-port", network::ports::DEFAULT_SOCKS)
    }

    #[must_use]
    pub fn guard_port(config: &Mapping) -> u16 {
        guard_u16(config, "port", network::ports::DEFAULT_HTTP)
    }

    #[must_use]
    pub fn guard_server_ctrl(config: &Mapping) -> String {
        config
            .get("external-controller")
            .and_then(Value::as_str)
            .and_then(|value| {
                let value = value.trim();
                let value = if value.starts_with(':') {
                    format!("127.0.0.1{value}")
                } else {
                    value.to_owned()
                };
                SocketAddr::from_str(&value).ok().map(|socket| socket.to_string())
            })
            .unwrap_or_else(|| network::DEFAULT_EXTERNAL_CONTROLLER.into())
    }

    #[must_use]
    pub fn guard_client_ctrl(config: &Mapping) -> String {
        let value = Self::guard_server_ctrl(config);
        match SocketAddr::from_str(&value) {
            Ok(mut socket) => {
                if socket.ip().is_unspecified() {
                    socket.set_ip(IpAddr::V4(Ipv4Addr::new(127, 0, 0, 1)));
                }
                socket.to_string()
            }
            Err(_) => network::DEFAULT_EXTERNAL_CONTROLLER.into(),
        }
    }
}

fn guard_u16(config: &Mapping, key: &str, default: u16) -> u16 {
    let port = config.get(key).and_then(value_to_u16).unwrap_or(default);
    if port == 0 { default } else { port }
}

fn value_to_u16(value: &Value) -> Option<u16> {
    match value {
        Value::String(value) => value.parse().ok(),
        Value::Number(value) => value.as_u64().and_then(|value| u16::try_from(value).ok()),
        _ => None,
    }
}

fn scalar_to_string(value: &Value) -> Option<String> {
    match value {
        Value::String(value) => Some(value.clone()),
        Value::Bool(value) => Some(value.to_string()),
        Value::Number(value) => Some(value.to_string()),
        _ => None,
    }
}

#[derive(Default, Debug, Clone, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct ClashInfo {
    pub mixed_port: u16,
    pub socks_port: u16,
    pub port: u16,
    pub server: String,
    pub secret: Option<String>,
}

#[derive(Default, Debug, Clone, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "kebab-case")]
pub struct IClash {
    pub mixed_port: Option<u16>,
    pub socks_port: Option<u16>,
    pub port: Option<u16>,
    pub allow_lan: Option<bool>,
    pub log_level: Option<String>,
    pub ipv6: Option<bool>,
    pub mode: Option<String>,
    pub external_controller: Option<String>,
    pub secret: Option<String>,
    pub dns: Option<IClashDNS>,
    pub tun: Option<IClashTUN>,
    pub interface_name: Option<String>,
}

#[derive(Default, Debug, Clone, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "kebab-case")]
pub struct IClashTUN {
    pub enable: Option<bool>,
    pub stack: Option<String>,
    pub auto_route: Option<bool>,
    pub auto_detect_interface: Option<bool>,
    pub dns_hijack: Option<Vec<String>>,
}

#[derive(Default, Debug, Clone, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "kebab-case")]
pub struct IClashDNS {
    pub enable: Option<bool>,
    pub listen: Option<String>,
    pub default_nameserver: Option<Vec<String>>,
    pub enhanced_mode: Option<String>,
    pub fake_ip_range: Option<String>,
    pub use_hosts: Option<bool>,
    pub fake_ip_filter: Option<Vec<String>>,
    pub nameserver: Option<Vec<String>>,
    pub fallback: Option<Vec<String>>,
    pub fallback_filter: Option<IClashFallbackFilter>,
    pub nameserver_policy: Option<Vec<String>>,
}

#[derive(Default, Debug, Clone, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "kebab-case")]
pub struct IClashFallbackFilter {
    pub geoip: Option<bool>,
    pub geoip_code: Option<String>,
    pub ipcidr: Option<Vec<String>>,
    pub domain: Option<Vec<String>>,
}

#[cfg(test)]
mod tests {
    use std::path::Path;

    use serde_yaml_ng::{Mapping, Value};

    use crate::constants::tun;

    use super::{ClashInfo, IClashTemp};

    #[test]
    fn default_template_has_stable_client_info() {
        let info = IClashTemp::template().get_client_info();

        assert_eq!(
            info,
            ClashInfo {
                mixed_port: 7897,
                socks_port: 7898,
                port: 7899,
                server: "127.0.0.1:9097".into(),
                secret: Some("set-your-secret".into()),
            }
        );
    }

    #[test]
    fn default_template_includes_tun_defaults() -> Result<(), &'static str> {
        let template = IClashTemp::template();
        let tun_config = template
            .0
            .get("tun")
            .and_then(Value::as_mapping)
            .ok_or("tun defaults")?;

        assert_eq!(tun_config.get("enable"), Some(&Value::from(false)));
        assert_eq!(tun_config.get("stack"), Some(&Value::from(tun::DEFAULT_STACK)));
        assert_eq!(tun_config.get("auto-route"), Some(&Value::from(true)));
        assert_eq!(tun_config.get("strict-route"), Some(&Value::from(false)));
        assert_eq!(tun_config.get("auto-detect-interface"), Some(&Value::from(true)));
        assert_eq!(
            tun_config.get("dns-hijack").and_then(Value::as_sequence).map(Vec::len),
            Some(tun::DNS_HIJACK.len())
        );
        Ok(())
    }

    #[test]
    #[cfg(unix)]
    fn ipc_template_does_not_expose_tcp_external_controller() {
        let template = IClashTemp::template_with_ipc(Some(Path::new("/tmp/app_settings.sock")));

        assert!(template.0.get("external-controller").is_none());
        assert!(template.0.get("external-controller-cors").is_none());
        assert_eq!(
            template.0.get("external-controller-unix"),
            Some(&Value::from("/tmp/app_settings.sock"))
        );
    }

    #[test]
    #[cfg(unix)]
    fn ipc_mapping_strips_stale_external_controller_fields() {
        let mut map = Mapping::new();
        map.insert("external-controller".into(), Value::from("0.0.0.0:8080"));
        map.insert("external-controller-cors".into(), Value::Mapping(Mapping::new()));

        let config = IClashTemp::from_mapping(map, Some(Path::new("/tmp/app_settings.sock")));

        assert!(config.0.get("external-controller").is_none());
        assert!(config.0.get("external-controller-cors").is_none());
        assert_eq!(
            config.0.get("external-controller-unix"),
            Some(&Value::from("/tmp/app_settings.sock"))
        );
    }

    #[test]
    fn invalid_ports_fall_back_instead_of_wrapping() {
        let mut map = Mapping::new();
        map.insert("mixed-port".into(), Value::from(65537_u64));
        map.insert("socks-port".into(), Value::from(0_u64));
        map.insert("port".into(), Value::from("abc"));
        map.insert("external-controller".into(), Value::from("0.0.0.0:8080"));

        let info = IClashTemp(IClashTemp::guard(map)).get_client_info();

        assert_eq!(info.mixed_port, 7897);
        assert_eq!(info.socks_port, 7898);
        assert_eq!(info.port, 7899);
        assert_eq!(info.server, "127.0.0.1:8080");
    }
}
